jobs:
- job: ApplyTerraform
  displayName: 'Apply Terraform Configuration'
  pool:
    name: Agent-AzDevOps

  steps:
  - checkout: self

  - script: |
      cd terraform
      echo resource_group_name  = "Seb-RG" > backend.config
      echo storage_account_name = "sebterraformstorage" >> backend.config
      echo container_name       = "tfstate" >> backend.config
      echo key                  = "terraform.tfstate" >> backend.config
      echo access_key           = "$(backend_access_key)" >> backend.config

      terraform init -backend-config=backend.config
      terraform plan -out=tfplan
      terraform apply -auto-approve tfplan
    displayName: 'Terraform Init, Plan & Apply'
    env:
      ARM_CLIENT_ID: $(ARM_CLIENT_ID)
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
      ARM_TENANT_ID: $(ARM_TENANT_ID)
      TF_VAR_backend_access_key: $(backend_access_key)
