jobs:
- job: ApplyTerraform
  pool:
    name: Agent-AzDevOps
  steps:
  - script: |
      dir
      terraform init
      terraform apply -auto-approve
    displayName: 'Apply Terraform'
    workingDirectory: $(System.DefaultWorkingDirectory)
