jobs:
- job: ApplyTerraform
  pool:
    name: Agent-AzDevOps
  steps:
  - script: |
      cd terraform
      dir
      echo %PATH%
      az version
      terraform init
      terraform apply -auto-approve
    displayName: 'Apply Terraform'
