jobs:
- job: ApplyTerraform
  displayName: 'Apply Terraform Configuration'
  pool:
    name: Agent-AzDevOps

  steps:
  - checkout: self

  - script: |
      echo "##[group]Chemin actuel et contenu"
      cd terraform
      dir
      echo "##[endgroup]"

      echo "##[group]Variables d’environnement ARM"
      echo %ARM_CLIENT_ID%
      echo %ARM_SUBSCRIPTION_ID%
      echo %ARM_TENANT_ID%
      echo "##[endgroup]"

      terraform init
      terraform apply -auto-approve
    displayName: 'Terraform Init & Apply'
    env:
      ARM_CLIENT_ID: $(ARM_CLIENT_ID)
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
      ARM_TENANT_ID: $(ARM_TENANT_ID)
      TF_VAR_backend_access_key: $(backend_access_key)
