version: "3.9"

services:
  simulator:
    build: .
    container_name: iot_simulator
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - weather_net
#
#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    volumes:
#      - /home/ubuntu/Back/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
#      - prometheus_data:/prometheus
#    ports:
#      - "9090:9090"
#    networks:
#      - weather_net
#
#  grafana:
#    image: grafana/grafana:latest
#    container_name: grafana
#    ports:
#      - "3000:3000"
#    volumes:
#      - grafana_storage:/var/lib/grafana
#    restart: unless-stopped
#    networks:
#      - weather_net

#volumes:
#  prometheus_data:
#  grafana_storage:

networks:
  weather_net:
    external: true
