services:
  simulator:
    build: .
    container_name: iot_simulator
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - weather_net

networks:
  weather_net:
    external: true
