version: 2.1

jobs:
  # Job pour installer les dépendances, analyser le code et lancer les tests
  lint_and_test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Installer les dépendances
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
      - run:
          name: Analyser le code avec pylint
          command: |
            . venv/bin/activate
            pip install pylint
            pylint IotWeather  # Remplace par ton répertoire de code
      - run:
          name: Exécuter les tests avec pytest
          command: |
            . venv/bin/activate
            pytest --maxfail=1 --disable-warnings -q  # Limiter à 1 échec, désactiver les avertissements

  # Job pour générer le changelog
  changelog:
    docker:
      - image: node:14
    steps:
      - checkout
      - run:
          name: Installer standard-version
          command: |
            npm install -g standard-version
      - run:
          name: Générer et committer le changelog
          command: |
            standard-version --first-release
            git commit -m "chore(release): $CIRCLE_SHA1"
            git push origin main  # Pousser les changements sur la branche main

  # Job pour afficher le badge de statut
  status:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Afficher l'URL du badge
          command: |
            echo "Status badge URL: https://img.shields.io/circleci/build/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/latest"

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint_and_test
      - changelog:
          requires:
            - lint_and_test  # Le job changelog dépend du job lint_and_test (si les tests passent)
      - status:
          requires:
            - changelog  # Affiche le badge après la génération du changelog
